sudo: required
language: generic

services:
    - docker

before_install:
    - docker build -t rishiksaran/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true rishiksaran/react-test npm run test

after_success:
    - docker build -t rockerid/multi-client ./client
    - docker build -t rockerid/multi-nginx ./nginx
    - docker build -t rockerid/multi-server ./server
    - docker build -t rockerid/multi-worker ./worker
    #Log in to the docker CLI
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    #Take the above built images and push them to docker hub
    - docker push rockerid/multi-client
    - docker push rockerid/multi-nginx
    - docker push rockerid/multi-server
    - docker push rockerid/multi-worker


#deploy:
#    provider: elasticbeanstalk
#    region: "us-west-2"
#    app: "docker-react"
#    env: "Docker-env"
#    bucket_name: "S3 bucket name"
#    bucket_path: "docker-react"
#    on:
#        branch: master
#    access_key_id: $AWS_ACCESS_KEY
#    secret_access_key: 
#        secure: "$AWS_SECRET_KEY"